### ISSUE TITLE
`math.MaxUint64` is not itself a `uint64` value

### ISSUE THREAD

**Issue by peterhellberg** [sqids/sqids-go#5]
As illustrated by this example: 

#### https://go.dev/play/p/tckABU8iLbW
```go
package main

import (
	"fmt"
	"math"
)

func MaxValue() uint64 {
	return math.MaxUint64
}

func main() {
	fmt.Println(MaxValue()+1 > MaxValue())
}
```
```
false
```

Adding `1` to the maximum value of a 64 bit unsigned integer in Go will result in it wrapping around, something the current code does not seem to take into consideration in code such as:

```go
if numbers[0]+1 > MaxValue() {
	return "", errors.New("ran out of range checking against the blocklist")
}
```

**Comment by 4kimov** [comment]
Uh oh, good catch. How do we fix that?

**Comment by peterhellberg** [comment]
Will be "solved" by not doing additions past the maximum `uint64` value in the library after #10
