### ISSUE TITLE
Fuzz testing of the library

### ISSUE THREAD

**Issue by peterhellberg** [sqids/sqids-go#6]
The Go toolchain has built in support for [fuzzing](https://go.dev/security/fuzz/), so we should at least add a test of `sqids.Encode` and possibly also `sqids.Decode`

_(I intend to open a PR for this in a bit)_

**Comment by peterhellberg** [comment]
A quick experiment shows that a corpus input such as: 
```go
go test fuzz v1
string("³102")
int(1)
string("77\xb17\x927\x9b777777\xf5\x9b7\xf077\xc4\xff\x82\xe17\xed\xe3\xe9\xce7\xc677")
uint64(94)
```
Would hang or terminate unexpectedly.

**Comment by 4kimov** [comment]
This is a great catch. I'm not sure I understand how those integers play a role, but decoding a string properly is always tricky and if a bug is caught, we should propagate it up to the spec too so other libs can fix.

**Comment by peterhellberg** [comment]
I'll open a PR for this as mentioned, but probably not tonight :)

**Comment by peterhellberg** [comment]
Encoding `99` using the alphabet `ë1092` results in `029\xc399` which can not be decoded with `v0.3.1`

**Comment by peterhellberg** [comment]
It should be noted that [`len("abcd€")`](https://go.dev/play/p/Yneo-slE77x) in Go does not return `5` but `7`, since that string is `7` bytes long, but 5 runes.

**Comment by 4kimov** [comment]
Looks like `ë` might be a multibyte char of `0xc3 0xab`? That's something we [don't support](https://github.com/orgs/sqids/discussions/1).

**Comment by peterhellberg** [comment]
@4kimov Yes, good to know that we only need to support singly byte characters in alphabets. Will add a check for this in the constructor.

**Comment by peterhellberg** [comment]
@4kimov So the "Bars" example on the [playground](https://sqids.org/playground) should not be valid then? Since `▁▂▃▄▅▆▇█`  are all multibyte characters.

**Comment by 4kimov** [comment]
Yes, I think so. It will be. Right now just removed it for the new algo: https://sqids.org/playground/simpler
